language: node_js
after_success:
  - mkdir /home/travis/tmp
  - sudo $(which npm) install -g firebase-tools
  - if [[ "${TRAVIS_PULL_REQUEST}" == "false" ]]; then echo -e "${FIREBASE_EMAIL}\n${FIREBASE_PASSWORD}" | firebase deploy; fi
